### ISSUE TITLE
About dof of robots and observation_space dimensions.

### ISSUE THREAD

**Issue by Xianqi-Zhang** [carlosferrazza/humanoid-bench#11]
Hi, 
Thanks for your sharing. 

1. As described on the [unitree H1 website](https://www.unitree.com/cn/h1/), the dof of each leg is 5 (Hip×3 + Knee×1 + Ankle×1) and the dof of each arm is 4, i.e., a total of 18 dof. But the dof of H1 is 26 in the code, so what positions do the other dof correspond to?
https://github.com/carlosferrazza/humanoid-bench/blob/3951d65bc85e16a562d091a7f4820150c20ed91f/humanoid_bench/robots.py#L1-L2

2. The dof of [H1Hand, H1Touch, H1Strong] is set to 76, they are H1 with 2 hands. In the [paper](https://arxiv.org/pdf/2403.10506), "..., additional 42-DoFs with two dexterous Shadow Hands..." (page 8, under Fig.7). But 26 (H1) + 42 (two dexterous Shadow Hands) is 68. Where are the remaining dof?

https://github.com/carlosferrazza/humanoid-bench/blob/3951d65bc85e16a562d091a7f4820150c20ed91f/humanoid_bench/robots.py#L75-L84

**If possible, could you tell me the corresponding relationship between each value (dof) and joint?**
https://github.com/carlosferrazza/humanoid-bench/blob/3951d65bc85e16a562d091a7f4820150c20ed91f/humanoid_bench/envs/basic_locomotion_envs.py#L22-L26

3. As illustrated in the [paper](https://arxiv.org/pdf/2403.10506), observations related part, " Proprioceptive robot state (i.e. joint angles and velocities) and task-relevant environment observations (i.e. object poses and velocities)." In envs, the observation_space() often use `self.robot.dof * 2 - 1` and `self.dof * 2 - 1`. What does `-1` correspond to?

https://github.com/carlosferrazza/humanoid-bench/blob/3951d65bc85e16a562d091a7f4820150c20ed91f/humanoid_bench/envs/basic_locomotion_envs.py#L35
https://github.com/carlosferrazza/humanoid-bench/blob/3951d65bc85e16a562d091a7f4820150c20ed91f/humanoid_bench/envs/powerlift.py#L41
https://github.com/carlosferrazza/humanoid-bench/blob/3951d65bc85e16a562d091a7f4820150c20ed91f/humanoid_bench/envs/basketball.py#L45

Thanks for your any reply.
Best regards.

The picture is h1 robot, and 'x' is the dof I marked (rotation joint, 1 dof), maybe not right.
![h1_x](https://github.com/carlosferrazza/humanoid-bench/assets/32128662/6e1a5e5a-6446-4992-8c4f-8e67374f8ad6)

**Comment by carlosferrazza** [comment]
Hi @Xianqi-Zhang, in the code we set the `dof` variable with the number of positional degrees of freedom. For the H1 robot, the velocities are one less than `dof` (due to using cartesian angular velocities as opposed to quaternions). This is why we often use the formulation `2 * dof - 1` to compute the robot state as the concatenation of positions and velocities.

With regard to your second post, as noted in the paper, see Table III in the appendix, the Shadow Hands add additional 50 dofs to the environment.

An important clarification to make is that with `dof` in the code we essentially refer to the length of `qpos`, while in the paper the dofs are always referring to the cartesian space (i.e., equal to the length of `qvel` in Mujoco). Hope this helps!

**Comment by carlosferrazza** [comment]
````
Robot: H1
Actuators: 19
qpos size: 26
	- Body: 19
        - Base Position + Orientation: 3 + 4 = 7  
--> 19 + 7 = 26
````

The Shadow Hands are underactuated:
````
Robot: H1hand
Actuators: 61 
       - Body: 19
       - Wrists: 2 (left and right)
       - Hands: 20 * 2 = 40
qpos size: 76
	- Body: 19
	- Wrists: 2 (left and right)
	- Hands: 24 * 2 = 48
        - Base Position + Orientation: 3 + 4 = 7
````
